#variable: mainvar testVarImage
#onSet: Une variable dans le fichier principal.
#onUnset: Un meurtre!
#value: false

#variable: otherVar testVarImage
#onSet: Une variable dans le fichier principal.
#onUnset: Un meurtre!
#value: true

#room: Placeholder
#description: Placeholder.
#contents:

#choice: Truc
#description: Machin
#body: Le château de senarclens est en afrique du sud.
Si, si, je vous assure.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: none
