#room: Plus loin dans la grande rue
#description: La rue était éclairée par la lumière blafarde des lampadaires sur ses côtés. Sur l'un d'entre eux, une affiche flottait dans le vent.
#contents:

#choice: Aller lire l'affiche sur le lampadaire
#description: Un des deux morceaux de ruban adhésif qui la maintenait s'étant cassé, elle flottait dans le léger vent du soir.
#body: Malmenée par les éléments, l'affiche disait:

AVEZ-VOUS VU CE CHAT
VU POUR LA DERNIÈRE FOIS CHEZ-
IL S'APPELLE CARAM-
CONTACTEZ R-

Une photo délavée figurait en haut; elle avait déteint sur le texte, rendant une partie illisible.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueLampadaires2

#choice: Revenir en arrière
#description: Il y avait encore des choses à voir, plus tôt sur le chemin.
#body: La femme revint sur ses pas, vers le kiosque.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueLampadaires1

#choice: Continuer dans la rue
#description: Plus avant, le bout de la rue.
#body: Devant la femme, une route barrait le passage; c'était le bout de la rue.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueLampadaires3
