#room: La grande rue
#description: Dans la rue vide, rien ne bougeait. Un kiosque fermé se trouvait au bord de la rue.
#contents:

#choice: Aller voir le kiosque
#description: Il était fermé depuis des heures, bien sûr. Quelqu'un avait oublié une affiche du journal du jour sur un des panneaux.
#body: L'affiche était celle d'un journal dont la une révélait ce dont tous s'inquiétaient:


QUI EST LE VOLEUR DE CHATS
Nos pistes sur l'affaire des disparitions récentes§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueLampadaires1

#choice: Aller plus loin dans la rue
#description: Le vent soufflait, faisant bouger l'affiche accrochée à un des lampadaires.
#body: La rue était bordée de lampadaires qui jetaient une lumière blafarde sur les pavés et les fenêtres fermées. À un de ces lampadaires était accrochée une affiche que le vent secouait.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueLampadaires2
