#room: Plus loin dans la grande rue
#description: La rue était éclairée par la lumière blafarde des lampadaires sur ses côtés. Sur l'un d'entre eux, une affiche flottait dans le vent. Plus loin, un passage menait à la ruelle de l'appartement de la femme.
#contents:

#choice: Aller lire l'affiche sur le lampadaire
#description: Un des deux morceaux de ruban adhésif qui la maintenait s'étant cassé, elle flottait dans le léger vent du soir.
#body: Malmenée par les éléments, l'affiche disait:

AVEZ-VOUS VU CE CHAT
VU POUR LA DERNIÈRE FOIS CHEZ-
IL S'APPEL-
CONTACTEZ R-

Une photo délavée figurait en haut; elle avait déteint sur le texte, rendant une partie illisible.
Pour l'instant, ce chat resterait sans nom.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueLampadaires2

#choice: Revenir en arrière
#description: Il y avait encore des choses à voir, plus tôt sur le chemin.
#body: La femme revint sur ses pas, vers le kiosque.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueLampadaires1

#choice: Aller dans la ruelle
#description: À gauche, la petite entrée d'une ruelle. Dans cette ruelle, le repos après une longue journée.
#body: La femme entra dans la ruelle. Elle était bientôt chez elle.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueLampadaires3
