#variable: rues none
#onSet: Vous êtes dans les rues de la ville.
#onUnset: Vous n'êtes plus dans les rues de la ville.
#value: true

#variable: appartement none
#onSet: Vous êtes chez vous.
#onUnset: Vous n'êtes plus chez vous.
#value: false

#variable: observeParChat none
#onSet: On vous observait.
#onUnset: On vous observe.
#value: false

#variable: verifierLait none
#onSet: Allez voir le bol de lait sur la fenêtre avant d'aller dormir.
#onUnset: Vous avez vérifié le bol de lait.
#value: false

#variable: remplirLait none
#onSet: Laissez un bol de lait avant d'aller dormir.
#onUnset: Vous avez rempli le bol de lait.
#value: false

#variable: enTrainDeDormir none
#onSet: Vous êtes en train de dormir.
#onUnset: Vous êtes réveillée.
#value: false

#variable: toits none
#onSet: Vous êtes sur les toits de la ville.
#onUnset: Vous n'êtes plus sur les toits de la ville.
#value: false

#room: Variables
#description: Placeholder
#contents:

#choice: Placeholder
#description: Placeholder
#body: nope§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: none
