#variable: rues none
#onSet: Vous êtes dans les rues de la ville.
#onUnset: Vous n'êtes plus dans les rues de la ville.
#value: true

#variable: appartement none
#onSet: Vous êtes chez vous.
#onUnset: Vous sortez de chez vous.
#value: false

#variable: observeParChat none
#onSet: On vous observait.
#onUnset: On vous observe.
#value: false

#variable: faireLait none
#onSet: Laissez un bol de lait avant d'aller dormir.
#onUnset: Vous pouvez allez dormir.
#value: false

#room: Variables
#description: Placeholder
#contents:

#choice: Placeholder
#description: Placeholder
#body: nope§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: none
