#variable: rues none
#onSet: Vous êtes dans les rues de la ville.
#onUnset: Vous n'êtes plus dans les rues de la ville.
#value: true

#variable: appartement none
#onSet: Vous êtes chez vous.
#onUnset: Vous n'êtes plus chez vous.
#value: false

#variable: observeParChat none
#onSet: On vous observait.
#onUnset: On vous observe.
#value: false

#variable: verifierLait none
#onSet: Allez voir le bol de lait sur la fenêtre avant d'aller dormir.
#onUnset: Vous avez rempli le bol de lait.
#value: false

#variable: enTrainDeDormir none
#onSet: Vous êtes en train de dormir.
#onUnset: Vous êtes réveillée.
#value: false

#variable: toits none
#onSet: Vous êtes sur les toits de la ville.
#onUnset: Vous n'êtes plus sur les toits de la ville.
#value: false

#variable: phase1 none
#onSet: Vous cherchez 3 raisons pour lesquelles les chats devraient faire sécession des humains.
#onUnset: Vous avez trouvé 3 raisons pour lesquelles les chats devraient faire sécession des humains.
#value: false

#variable: phase2 none
#onSet: Vous cherchez 3 raisons pour lesquelles les chats devraient rester auprès des humains.
#onUnset: Vous avez trouvé 3 raisons pour lesquelles les chats devraient rester auprès des humains.
#value: false

#variable: phase3 none
#onSet: Vous devez aller chercher les affiches.
#onUnset: Vous avez les affiches.
#value: false

#variable: raisonPartirAnimalerie none
#onSet: Vous avez trouvé une raison de partir en voyant la vitrine d'une animalerie.
#onUnset: Il vous manque une raison de partir.
#value: false

#variable: raisonPartirVeterinaire none
#onSet: Vous avez trouvé une raison de partir en voyant l'affiche d'un cabinet de vétérinaire.
#onUnset: Il vous manque une raison de partir.
#value: false

#variable: raisonPartirMaison none
#onSet: Vous avez trouvé une raison de partir en regardant par la fenêtre d'une maison.
#onUnset: Il vous manque une raison de partir.
#value: false

#variable: raisonResterNourriture none
#onSet: Vous avez trouvé une raison de rester en regardant un sac de nourriture pour chat.
#onUnset: Il vous manque une raison de rester.
#value: false

#room: Variables
#description: Placeholder
#contents:

#choice: Placeholder
#description: Placeholder
#body: nope§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: none
