#room: Le moment du choix.
#description: La femme avait une suggestion.
#contents:

#choice: "Et si vous parliez?"
#description: Les chats étaient choqués.
#body: La femme dit: "Et si vous parliez? Vous avez une voix, pourquoi ne l'utilisez-vous pas pour demader ce que vous voulez à vos maîtres?"

Un autre chat répondit: "Nous ne pouvons pas. C'est trop dangereux."

"Pourquoi dangereux?"

"Notre voix est un secret. Nous avons convenu que nous ne parlerions jamais à un humains dans sa langue, car il pourrait nous utiliser. Notre liberté en tant qu'animaux domestiques est d'être inutiles. Les humains pensent que nous ne les comprenons pas. De ce fait, nous pouvons faire ce que nous voulons. S'ils savaient que nous pouvions parler, ils se méfieraient de nous, et ils essaieraient de nous utiliser. En ce moment, nous sommes juste adoptés pour occuper la vie des humains, ou, au mieux, pour attraper les rats. S'ils savaient ce que nous pouvions faire, ils nous utiliseraient comme espions ou pire. C'est plus simple de rester soumis. Simplement, nous ne pouvions plus le supporter, alors nous avons voulu partir."

"Si vous restez muets, vous ne pourrez pas changer quoi que ce soit, à part en partant."

"Ce sont nos deux seuls choix."

"Non. Vous avez le choix de choisir qui vous voulez être, ou de rejeter à la fois qui vous êtes et qui vous n'êtes pas. Si vous parlez, il n'y aura pas que des conséquences positives, c'est vrai. Mais les humains ont un défaut: ils n'écoutent que ce qui est comme eux. Et pour être humain, il faut pouvoir parler."

"Mais écouteront-ils ce que nous avons à dire?"

"Vous êtes dans chaque maison, aux côtés d'humains qui se soucient de vous et qui, pour certains, ont grandi avec vous. Si vous parlez tous, vous serez entendus. C'est une chance que beaucoup n'ont pas."

"Mais que dirons-nous aux humains?"

"Ce que vous voulez leur demander. D'avoir le contrôle de votre corps, d'être indépendants et libres de vos mouvements, de votre identité. Si vous rentrez chez vous ce matin et dites tout ça, vous changerez les choses."

Mra s'interposa: "Vous n'allez pas abandonner comme ça! Si nous partons ensemble, nous pourrons former une autre société, où nous n'aurons pas besoin de compromis. Où nous n'aurons plus besoin des humains. Ne trouvez-vous pas ça beau?"

L'assemblée resta silencieuse.

Mra termina: "Bande de lâches. L'aube est là. Il est temps de faire un choix; qui me soutient me suive."

Sur ce, elle se leva, alla à l'escalier et descendit du toit. Elle fut suivie par une poignée de chats. Le reste regarda la femme, qui parla:

"Votre futur est entre vos mains, maintenant. Il est temps de rentrer."

Un chat se leva et partit. Puis un autre, et encore un autre. Après un moment, il ne resta que la femme et Lucky sur le toit.

"Et toi, Lucky, tu ne rentres pas chez toi?"

"Je n'ose pas. J'ai peur de comment ils m'accueilleront."

"Ne t'inquiète pas, suis-moi."

Et ils y allèrent ensemble, sous le soleil levant.§
#image: none
#requirements: none
#visible: false
#sideeffects: unset toits, set appartement
#next: epilogue
