#room: La lecture des affiches.
#description: La femme lisait et les chats écoutaient, curieux.
#contents:

#choice: Plein d'affiches
#description: La femme lisait les affiches, une à une. Les chats écoutaient.
#body: La femme s'assit et commença à lire. Les chats l'écoutèrent énoncer le contenu de chaque affiche une à une.

"Avez vous vu ce chat? Il s'appelle Caramel. Si vous le voyez, contactez..." à l'évocation du nom, un chat se redressa.

"Chat perdu. Très timide, ne pas brusquer..." Elle montra la photo du haut de l'affiche. Un chat s'y reconnut.

"Si vous voyez mon chat, appelez ma maman. Son numéro c'est..." La femme montra le dessin sur l'affiche et pointa vers le dessin: "C'est marqué 'Sheena'. Une chatte dans le fond bougea.

Beaucoup d'affiches suivirent. Les chats, un à un, entendirent leur nom.

Enfin, le bout de la pile arriva: "Celle-ci a été imprimée beaucoup de fois, et collée partout."

"Chat tigré. Il a disparu depuis 2 mois, vu pour la dernière fois dans la rue grise. Il est très important pour moi et il me manque beaucoup. Si vous le voyez appelez-moi tout de suite à ce numéro... S'il vous plaît, si vous le voyez avertissez-moi, il compte tellement pour moi. Je veux au moins savoir s'il est en vie..."

Elle fit une pause, surprise, puis termina: "Son nom est Lucky."

Lucky regarda la femme en ouvrant grand les yeux, ému. Il ne dit rien.

L'audience était silencieuse. Tous pensaient à leurs maîtres, à leurs anciennes maisons. Mra intervint: "Allons donc, vous n'allez pas commencer à douter maintenant! Allez-vous vraiment changer d'avis à cause de quelques mots imprimés sur une feuille? Les humains vous opprimaient! Voulez-vous vraiment revenir chez eux pour poursuivre ce cycle?"

Les chats réfléchirent. Finalement, un parla: "Mra n'a pas tort. Nos maîtres nous manquent, mais si nous revenons vers eux, nous finirons comme nous avons commencé. Que pouvons-nous faire?"

Après un moment de réflexion, la femme parla.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: affiches2
