#room: Une allée pleine de magasins
#description: L'allée était un endroit au bord de la ville où l'on pouvait trouver de tout. Vêtements, nourriture, etc. À l'heure où ils passaient, tout était fermé. De l'agitation diurne, il ne restait que des vitrines noires et vides.
#contents:

#choice: Retourner vers la grande route
#description: Il y avait plus de choses à voir là-bas.
#body: §
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: grandeRoute
