#room: Chapitre 3: Les yeux de la ville
#description: Mra avait une proposition.
#contents:

#choice: "Va dans la ville..."
#description: "Découvre pourquoi nous partons."
#body: "Je n'ai aucune affinité pour toi, humaine, mais par égard l'attention que tu as portée aux autres chats sans jamais violer leur liberté, je ne peux pas t'exclure comme les autres humains.

Tous ici sauf moi te connaissent et t'apprécient. Pour porter leur gratitude, je vais te laisser voir ce qu'aucun autre humain dans la ville ne verra: pourquoi nous partons.

Certains d'entre nous ne sont pas encore arrivés. Nous avons lancé l'appel pour que tous les chats nous rejoignent il y a deux mois. Nous restons jusqu'à l'aube pour que les derniers nous rejoignent. Quand le soleil commencera à éclaircir l'horizon, nous partirons.

D'ici là, va dans la ville. Prends avec toi le traître, il te guidera. Reviens vers nous quand tu auras trouvé les raisons pour lesquelles nous voulons partir."

L'ordre avait été donné. Des chats s'écartèrent de devant l'escalier de secours. La mission était lancée.§
#image: none
#requirements: none
#visible: false
#sideeffects: set phase1
#next: chats
