#room: Chapitre 3: Les yeux de la ville
#description: MLa voix de Mra tonna.
#contents:

#choice: "Va-t-en."
#description: "Tu n'as rien  à faire ici."
#body: "Je ne sais pas ce que Lucky espérait en allant te chercher. Tu n'as jamais vécu comme nous. Tu n'as pas vu à travers nos yeux. Qu'as-tu l'orgueil de croire pouvoir nous dire? Tu n'as même pas quatre pattes pour bondir!

Elle continua: "Je te laisse ce moment pour partir, et que tu emmènes Lucky avec toi. Vous deux feriez bien de le prendre."

La femme recula de quelques pas. Lucky jeta un regard à Mra et se dirigea vers l'escalier de secours.

"Viens, humaine."

La femme et Lucky descendirent.

La femme demanda: "Donc c'est fini?"

Lucky se tourna vers elle et dit: "Absolument pas."

"Comment ça?"

"J'ai fait une erreur, humaine. Je me suis trop précipité. On va réessayer."

"Réessayer? Et qu'espères-tu? Me faire devenir un chat pour les convaincre?"

"Plus ou moins."

"...?"

"Allons marcher dans la ville. Je veux te faire comprendre pourquoi les autres veulent partir. Je pense que si on trouve trois raisons, ça sera assez pour te faire comprendre le message."

La femme réfléchit à ce changement de plan. Elle voulait que les chats restent.

"D'accord. Essayons ça."§
#image: none
#requirements: none
#visible: false
#sideeffects: set phase1, unset toits, set rues
#next: ruelleOubliee
