#room: Un cul de sac
#description: C'était le bout de la rue. Il y avait, serrée entre trois murs de brique décrépite, une benne à ordures.
#contents:

#choice: Retourner dans la rue grise
#description: Il y aurait plus de choses à voir là-bas.
#body: La femme retourna dans la rue grise, rejoignant Lucky qui voulait s'éloigner le plus vite possible.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueGrise
