#room: La grande route
#description: La route coupait la grande rue pour se diriger au loin. Un embranchement allait vers une allée bordée de magasins. Dans l'autre direction, La route menait à un quartier résidentiel.
#contents:

#choice: Aller dans le quartier résidentiel
#description: C'était un quartier moderne, construit il y quelques années.
#body: Ils montèrent la route et arrivèrent sur une place éclairée par des lampes aux couleurs chaudes. Le quartier était très vaste.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: quartierSpacieux

#choice: Aller dans l'allée aux magasins
#description: Bordée de boutiques en tous genres.
#body: Ils traversèrent en vitesse la route vide, et arrivèrent jusqu'à l'allée.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: alleeMagasins

#choice: Aller dans la grande rue
#description: Vers les lampadaires.
#body: Ils retournèrent à la grande rue.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: grandeRue3
