#room: La grande rue
#description: La grande rue était aussi vide et immobile qu'avant. Un kiosque fermé se trouvait au bord de la rue.
#contents:

#choice: Aller voir le kiosque
#description: Il était fermé depuis des heures, bien sûr. Quelqu'un avait oublié une affiche du journal du jour sur un des panneaux.
#body: L'affiche était celle d'un journal dont la une révélait ce dont tous s'inquiétaient. Ils ne savaient pas à quel point ils étaient loin du compte.


QUI EST LE VOLEUR DE CHATS
Nos pistes sur l'affaire des disparitions récentes

p. 3: Statistiques: 90 pourcents des chats disparus dans la Ville?

p.6: Un témoignage: "Nous gardons le nôtre avec nous en tout temps, on a tellement peur qu'il disparaisse"

Lucky regarda l'affiche d'un air ennuyé, puis partit sans faire de commentaire.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: grandeRue1

#choice: Aller dans une rue tortueuse
#description: La rue partait vers la droite en suivant une forme étrange.
#body: Ils s'engagèrent dans la rue tortueuse.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueTortueuse

#choice: Retourner dans la rue grise
#description: Il était temps de revenir vers les chats.
#body: Ils prirent la grande rue grise qui partait à gauche.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueGrise

#choice: Aller plus loin dans la rue
#description: Le vent soufflait, faisant bouger l'affiche accrochée à un des lampadaires.
#body: La rue était bordée de lampadaires qui jetaient une lumière blafarde sur les pavés et les fenêtres fermées. À un de ces lampadaires était accrochée une affiche que le vent secouait.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: grandeRue2
