#room: La grande route
#description: 
#contents:

#choice: Aller dans le quartier spacieux
#description: 
#body: §
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: quartierSpacieux

#choice: Aller dans l'allée aux magasins
#description: 
#body: §
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: alleeMagasins

#choice: Aller dans la grande rue
#description: 
#body: §
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: grandeRue3
