#room: Un parc public
#description: 
#contents:

#choice: S'asseoir sur un banc
#description: Il y avait toujours un moment pour reprendre son souffle...
#body: La femme s'assit sur un des bancs du parc. Lucky sauta sur le banc et se coucha à côté d'elle. Cela faisait déjà un moment qu'ils marchaient dans la ville.

"Comment est-ce qu'on va faire?", dit la femme. Elle n'avait pas d'idées.

Mais Lucky ne l'écoutait pas.

"Qu'est-ce que tu regardes?"

Elle suivit son regard. À une dizaine de mètres, un homme qui se promenait regardait à ses pieds, franchement surpris. Un chat se frottait à ses pieds.

"Ah."

Lucky parla doucement: "Je le connais de loin. Il était sur le toit tout à l'heure."

Le chat qui se frottait aux pieds de l'homme le regarda une fois, puis s'enfuit en courant, avant que ce dernier puisse le suivre. L'homme fit un geste vers le chat, mais voyant qu'il ne pourrait pas rattraper ce dernier, il resta juste coi au bord du parc.

"Un chat qui a voulu saluer une dernière fois son maître avant de partir. Malgré les discours de Mra, je pense que beaucoup tenaient autant à leur maître que moi."§
#image: none
#requirements: yes phase2, no raisonResterAmour
#visible: false
#sideeffects: set raisonResterAmour
#next: parcPublic

#choice: Retourner vers le quartier
#description: Il n'y avait rien d'autre à voir dans le parc, à cette heure-là.
#body: Ils retournèrent au quartier résidentiel.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: quartierSpacieux
