#room: Un quartier spacieux
#description: Le quartier était récent, habité depuis quelques années. Il était bien éclairé et incroyablement spacieux. Les abris à vélos étaient vides et les rideaux de la plupart des appartements étaient tirés.
#contents:

#choice: Aller dans le parc
#description: Au milieu du quartier, il y avait un petit parc à l'intention des habitants.
#body: Ils se rapprochèrent du parc. Un homme promenait son chien. Ce dernier et Lucky se fixèrent froidement jusqu'à ce que le maître du chien parte, après quoi son animal de compagnie le suivit.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: parcPublic

#choice: Aller vers la route
#description: Ils avaient fait tout ce qu'ils avaient à faire là.
#body: Ils revinrent vers la route, de la lumière à la nuit noire.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: grandeRoute
