#room: "Voilà pourquoi vous devriez rester..."
#description: Le premier argument n'avait pas bien marché. Vite, au suivant.
#contents:

#choice: "Pensez à la compagnie de vos anciens maîtres."
#description: Peut-être cela éveillera-t-il de bons souvenirs.
#body: Lucky continua: "Pensez à vos maîtres. Votre famille. Ne vous manquent-ils pas? Ne vous languissez-vous pas d'une présence chaude contre laquelle venir lorsque la fatigue vient? Ne vous languissez-vous pas des caresses douces de ceux qui étaient votre famille?"

"Ce sont des choses du passé, renégat, répondit Mra. Nous sommes des chats, et désormais, entre chats nous resterons. Nous sommes plus que pleinement capables d'être notre propre famille sans se reposer sur des espèces inférieures. En tant que chats, nous nous comprenons mieux qu'un humain nous comprendra jamais."

"Est-ce vraiment le cas? Tout à l'heure, dans la ville, nous avons vu un chat qui était venu dire adieu à son maître. Nous doutons qu'il soit le seul. Chats, détestez-vous réellement vos maîtres autant que vous le prétendez?"

Mra feula: "Tu mens, traître. Sous-entends-tu que nous sommes de faible volonté? Tu cherches à semer le doute parmi nous. Contrairement à toi, je crois en mes gens."

Elle regarda autour d'elle, sonda la foule. Mais les regards avaient perdu en agressivité. Certains avaient même baissé les yeux. L'argument avait fait mouche.

Le chat que Lucky et la femme avaient vu au parc était vers le fond, interdit.§
#image: none
#requirements: yes raisonResterAmour
#visible: false
#sideeffects: none
#next: raisonDeRester3
