#room: "Voilà pourquoi vous devriez rester..."
#description: À l'estocade finale.
#contents:

#choice: "Pensez à combien vous leur manquez."
#description: Cela devrait marcher.
#body: Lucky assèna: "Vos maîtres, vos familles, pensez à ce qu'ils ont dû ressentir lorsque vous les avez quittés. Pensez à combien vous les rendiez heureux. Pensez à ce que vous pourriez changer en revenant vers eux."

Le regard de beaucoup finit de s'adoucir. Ils avaient les mêmes regrets que Lucky.

Mra sauta sur l'occasion: "C'est là où tu te trompes, traître. Les humains ont l'amour facile et faible. Ils ont imposé leurs voies dominantes sur les chats des années durant, et le jour où nous sommes partis, la plupart d'entre eux nous ont cherchés quelques heures, puis nous ont déclarés morts. Ils n'ont pas été capables de s'inquiéter pour nous une fois que nous sommes partis."

La femme l'interrompit: "Ils vous ont... déclarés morts? Pas du tout, ils se souciaient de vous et le font toujours maintenant! Qu'est-ce que tu racontes?"

Mra répondit: "Pour la plupart, ils nous ont à peine cherchés un jour. Après cela, ils ont collé une feuille avec notre tête dessus dans les rues, comme vous faites des statues de vos morts."

"Des... c'était des avis de recherche pour vous! Pas des épitaphes!"

"Des quoi, humaine?"

"Vous pouvez parler mais... ne savez pas lire?"

Lucky se tourna vers elle: "Nos maîtres nous parlaient, ils ne nous faisaient pas de leçons de lecture."

La femme marqua un temps de pause. Enfin, elle expliqua:

"Ces affiches qui sont collées partout dans les rues, avec des images de vous dessus. Ce sont des avis de recherche. Vos maîtres voulaient vous retrouver, alors ils ont accroché des affiches qui vous décrivaient. Elles demandaient à tous ceux qui les lisaient de contacter vos maîtres s'ils vous voyaient. À cause de leur travail, ils n'avaient pas le temps de vous chercher. Il y a eu une enquête pour vous. Des groupes de recherche volontaire. Comment ne les avez-vous pas vus?"

"Nous vivions cachés, en évitant les humains. Nous ne faisions pas attention à chaque groupe."

La femme eut une idée soudaine: "Je reviens tout de suite."

Lucky, confus, demanda: "Que vas-tu faire, humaine?"

"Viens avec moi. Nous allons leur ramener les affiches de la grande rue et les leur lire."§
#image: none
#requirements: yes raisonResterLucky
#visible: false
#sideeffects: set phase3
#next: chats
