#room: "Voilà pourquoi vous devriez rester..."
#description: Il fallait parler vite. Mra n'allait pas se laisser interrompre pendant longtemps.
#contents:

#choice: "Pensez au repas qui vous attendait quand vous rentriez chez vous le soir."
#description: Leur rappeler leur ancien chez-soi.
#body: Commencer par les arguments les moins forts. Un début.

"Pensez, dit Lucky, à votre ancienne maison. Pensez à quand vous rentriez chez vous le soir au chaud, et au bon plat que vous mangiez. N'avez-vous pas envie de revoir ça?"

L'expression d'une partie des chats passa de curieuse à agacée. Pour beaucoup, la nourriture n'était probablement pas aussi bonne que chez Lucky. Mra abattit l'argument:

"Tu veux les acheter avec de la nourriture? Vraiment?"

Il était temps de passer à l'argument suivant.§
#image: none
#requirements: yes raisonResterNourriture
#visible: false
#sideeffects: none
#next: raisonDeRester2
