#room: Une rue grise
#description: 
#contents:

#choice: Aller dans une ruelle oubliée
#description: 
#body: §
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: ruelleOubliee

#choice: Aller dans un cul de sac
#description: 
#body: §
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: culDeSac

#choice: Aller dans la grande rue
#description: 
#body: §
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: grandeRue1
