#room: Une rue grise
#description: Une rue grise et quelconque. Les maisons avaient soit les volets fermés, soit un noir profond derrière les vitres.
#contents:

#choice: Aller dans une ruelle oubliée
#description: Une ruelle sale et décrépite coincée entre deux bâtiments, où la lumière de la lune ne passait pas.
#body: La femme et Lucky allèrent dans la ruelle, s'enfonçant plus profondément dans l'ombre des recoins perdus de la ville.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: ruelleOubliee

#choice: Aller dans un cul de sac
#description: Le bout de la rue. Il n'y avait pas grand chose à voir, à part une benne à ordures.
#body: Ils se rapprochèrent du bout de la rue. À une certaine distance de la benne, la femme se boucha le nez pour échapper à l'odeur. Lucky, ne pouvant pas le faire, resta simplement en retrait.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: culDeSac

#choice: Aller dans la grande rue
#description: Sortir au clair de lune.
#body: Ils sortirent de la rue grise et entrèrent dans la grande rue, qui révérbérait l'éclat blanc de la lune.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: grandeRue1
