#room: La ruelle
#description: La ruelle était bordée de plusieurs maisons, dont la plupart des lumières étaient éteintes. Quelques affiches étaient collées aux murs. Au bout, l'entrée de l'immeuble de la femme.
#contents:

#choice: Rentrer chez soi
#description: Pas maintenant.
#body: La femme avait des choses à faire avant que la nuit ne se finisse. Ce n'était pas le moment de rentrer chez elle.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: ruelleMaison

#choice: Revenir en arrière
#description: Il n'y avait rien à voir ici.
#body: Ils revinrent vers la grande rue.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: grandeRue3
