#room: Une ruelle oubliée
#description: C'était une ruelle coincée entre deux immeubles anonymes. Sa seule caractéristique notable était qu'elle contenait l'escalier de secours d'un des immeubles. Et au sommet de cet immeuble, un rassemblement des chats de la ville, accessoirement.
#contents:

#choice: Remonter sur le toit de l'immeuble
#description: Il était temps de reparler aux chats.
#body: La femme monta les marches de l'escalier rapidement, Lucky plus lentement.§
#image: none
#requirements: none
#visible: false
#sideeffects: unset rues, set toits
#next: chats

#choice: Aller dans une rue grise
#description: Il n'allait pas se passer grand chose dans cette ruelle; il fallait sortir.
#body: La femme et Lucky sortirent de la ruelle vide, aboutissant dans une autre rue vide, et tout aussi anonyme.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueGrise
