#room: La ruelle
#description: La ruelle était bordée de plusieurs maisons, dont la plupart des lumières étaient éteintes. Quelques affiches étaient collées aux murs. Au bout, l'entrée de l'immeuble de la femme.
#contents:

#choice: Revenir en arrière
#description: Il n'y avait rien à voir ici.
#body: La femme revint sur ses pas, vers la grande rue.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: grandeRue3
