#room: "Pst, humaine!"
#description: Un appel derrière elle. Elle se retourna. C'était Lucky. Il avait quelque chose à dire.
#contents:

#choice: "Tout n'est pas perdu!"
#description: Il venait d'avoir une idée.
#body: "Humaine! Il y a peut-être une solution!"

"Une solution pour quoi?"

"Pour les faire rester!"

Elle marqua un temps de silence.

"Explique."

"Mra vient de l'extérieur. Elle nous a rasseblés pour partir parce qu'elle détestait les humains. Elle ne pouvait pas comprendre pourquoi on restait avec eux."

"Et?"

"Et la plupart des chats l'ont suivie pour une autre raison: ils voulaient ne plus dépendre d'un humain."

"N'est-ce pas la même chose?"

"Absolument pas. La plupart des chats ne détestent pas les humains, ils veulent juste pouvoir décider de leur vie. Ils ont suivi Mra parce qu'ils étaient d'accord avec son projet. Ils se sont persuadés des idées après."

"Et donc?"

"Je pense que beaucoup ont envie de revoir leur maître, mais sur des termes différents. Si on arrive à leur rappeler pourquoi ils aimaient les humains, peut-être que cette envie prendra le pas sur les projets de Mra."

"De combien de raisons a-t-on besoin?"

"Je pense que si on ne les convainc pas avec trois, on ne les convaincra pas."

"Va pour trois, alors."

"Parfait! Descendons dans les rues pour trouver des idées."§
#image: none
#requirements: none
#visible: false
#sideeffects: set phase2
#next: chats
