#room: Une rue en pente
#description: Ils étaient en haut d'une rue qui descendait en pente tout droit vers le centre ville. De là, on pouvait voir toute la ville en dessous.
#contents:

#choice: Retourner à la rue tortueuse
#description: "Où va-t-on?" demanda Lucky, confus.
#body: La femme fixa les grands immeubles au loin.

"Où va-t-on?" demanda Lucky, confus.

"Nulle part", répondit la femme, et elle revint sur ses pas.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueTortueuse
