#room: Derrière la porte
#description: La femme ouvrit la porte.
#contents:

#choice: C'était Lucky!
#description: Elle ne l'avait pas vu depuis longtemps.
#body: La femme ouvrit la porte. Elle baissa d'abord les yeux et vit Lucky. Elle était ravie de le voir; ils ne s'étaient pas revus depuis la grande nuit. Elle se baissa pour lui parler:

"Salut Lucky! Comment vas-tu?"

"Bien, humaine, mais regarde autour de toi. Je ne suis pas seul."

Elle regarda dans chaque direction du couloir de l'immeuble. Quelques silhouettes attendaient au fond du couloir.

"Vous pouvez venir, tout le monde!"

Les silhouettes commencèrent à s'approcher. C'était des chats. Et derrière eux, d'autres chats. Ils arrivèrent devant la porte d'entrée, et le couloir fut bientôt rempli de chats.

"Nous sommes venus te dire merci."

FIN§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: none
