#room: Épilogue
#description: Plusieurs semaines avaient passé. Un beau soir, à l'heure où le ciel terminait de rougir, la femme venait de rentrer chez elle.
#contents:

#choice: Lire le journal
#description: Un journal datant d'il y a quelques jours traînait encore sur la table.
#body: La une était aussi énergique que d'habitude:

LE MONDE POST-CHATS
Nos pistes sur le futur avec les animaux parlants p. 3

Un modèle: Un chat spécialiste du comportement animal à l'Université locale p. 7

Les chiens peuvent-ils aussi parler? p. 10
Un expert s'exprime: "Notre chat nous assure que non, mais on peut peut-être arriver à quelque chose."§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: epilogue

#choice: Vérifier le bol de lait sur la fenêtre
#description: Vide, comme tous les soirs lorsqu'elle rentrait.
#body: La femme sourit en voyant le bol vide. Elle le vérifiait en se réveillant et en rentrant chez elle le soir, et elle le trouvait toujours vide, depuis que les chats étaient revenus. Fatiguée ce soir-là, elle décida qu'elle le remplirait un peu plus tard.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: epilogue

#choice: Regarder par la fenêtre
#description: La ville était belle à ce moment là de la journée.
#body: La femme s'accouda à la fenêtre. Depuis son aventure avec Lucky, sa vision de la ville avait changé.§
#image: none
#requirements: none
#visible: true
#sideeffects: none
#next: epilogueFenetre

#choice: Ouvrir la porte
#description: Quelqu'un frappait à la porte.
#body: La femme alla ouvrir la porte, révélant...§
#image: none
#requirements: yes raisonResterLucky
#visible: true
#sideeffects: none
#next: epiloguePorte
