#room: Par la fenêtre
#description: Depuis la fenêtre, la ville s'étendait au loin, vaste et calme. Une légère brise rafraichissait l'atmosphère du début de l'été.
#contents:

#choice: Regarder les immeubles du centre-ville
#description: Au loin, la femme pouvait voir les lumières des immeubles du centre-ville. Derrière, les dernières lumières de la journée.
#body: Les immeubles brillaient au loin, mais il n'étaient que quelques formes qui de découpaient sur l'immense arrière-plan du ciel du crépuscule. De grands nuages roses le traversaient, suivant les traînées d'avions qui étaient passés il y a bien longtemps.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: epilogueFenetre

#choice: Regarder les étoiles
#description: Étoiles? Quelles étoiles? Si elles étaient invisibles dans le ciel, les lumières des fenêtres constellaient la terre.
#body: La femme leva les yeux vers le ciel. La lumière des maisons se réverbérait sur le ciel, rendant les étoiles invisibles. En lieu d'elles, les toits se dressaient comme des cimes à conquérir, et les fenêtres commes des astres. À les regarder, on pouvait se perdre dedans.

Elle eut envie de retourner se balader sur ces toits à l'instant même, comme elle avait pris pour habitude de faire après son escapade nocturne quelques semaines plus tôt. Ce soir-là, fatiguée, elle décida de ne pas le faire.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: epilogueFenetre

#choice: Regarder les rues en dessous
#description: En dessous de l'immeuble, la femme pouvait voir s'étaler le réseau complexe des rues de la ville.
#body: La femme baissa les yeux. En dessous d'elle, la toile des rues sombres, éclairées par endroits par des lampadaires. C'était une toile infinie de chemins enlacés qui n'attendait que d'être parcourue, pleine de recoins cachés. Véritablement, elle n'attendait qu'à être explorée.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: epilogueFenetre

#choice: Faire autre chose
#description: La femme aurait pu rêver des heures durant en regardant par la fenêtre, mais il était temps d'aller se reposer.
#body: Elle leva son coude du rebord de la fenêtre et se retourna vers le reste de l'appartement.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: epilogue
