#room: L'appartement
#description: a
#contents:

#choice: Un regard furtif
#description: La femme se retourna. Quelque chose la fixait depuis le buisson.
#body: La femme se retourna. Une figure grise parit en courant. Un chat. En ce moment? D'où venait-il?§
#image: none
#requirements: no observeParChat
#visible: false
#sideeffects: set observeParChat
#next: rueLampadaires4

#choice: Revenir en arrière
#description: Il y avait encore des choses à voir, plus tôt sur le chemin.
#body: La femme revint sur ses pas, vers la grande rue.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueLampadaires3
