#room: Par la fenêtre
#description: Depuis la fenêtre, la ville s'étendait au loin, vaste.
#contents:

#choice: Regarder les immeubles du centre-ville
#description: Au loin, la femme pouvait voir les lumières des immeubles du centre-ville.
#body: Au loin, la femme pouvait voir les lumières des immeubles du centre-ville. De grandes tours qui s'élevaient loin au dessus des petits immeubles de son quartier de banlieue.
En regardant bien, elle pouvait même distinguer le bâtiment où elle travaillait, une grande silhouette grise dont certaines fenêtres brillaient d'une lueur blanchâtre.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: appartementFenetre

#choice: Regarder les étoiles
#description: Étoiles? Quelles étoiles?
#body: La femme leva les yeux vers le ciel. La lumière des maisons se réverbérait sur le ciel, rendant les étoiles invisibles. Faiblement, on pouvait voir la lune, mais le reste du ciel était éteint par la lumière d'en dessous.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: appartementFenetre

#choice: Regarder les rues en dessous
#description: En dessous de l'immeuble, la femme pouvait voir s'étaler le réseau complexe des rues de la ville.
#body: La femme baissa les yeux. En dessous d'elle, la toile des rues sombres, éclairées par endroits par des lampadaires. Le tout ne faisait que souligner la saleté de l'endroit.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: appartementFenetre

#choice: Faire autre chose
#description: Il était beau de rêvasser en regardant par la fenêtre, mais il était temps de revenir au monde réel.
#body: La femme leva son coude du rebord de la fenêtre et se retourna vers le reste de l'appartement.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: appartement
