#room: Chapitre 1: Dans la rue...
#description: Tard le soir, dans la vaste ville, une jeune femme rentrait chez elle après une dure journée de travail. Le chemin pour rentrer chez elle passait par...
#contents:

#choice: La grande rue.
#description: Vide de monde, bordée par les lampadaires.
#body: La femme s'engagea dans la grande rue. À cette heure-ci, il n'y avait personne.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: rueLampadaires1
