#room: Un rêve de Sisyphe
#description: Dans les royaumes du rêve, les formes et idées défilaient librement. Cette nuit-ci, elles convergeaient vers un rocher en bas d'une rue en pente.
#contents:

#choice: Regarder autour de soi
#description: Tout autour, les immeubles se dressaient, menaçants. Entre eux, la rue montait, et en son creux, une boule de marbre.
#body: Tout autour, les silhouettes sombres des immeubles se dressaient, menaçantes.

Entre elles, la rue montait en pente raide aussi loin que portait la vue, bordée de voitures et de lampadaires.

Dans le creux en bas de la rue, où se trouvait la femme, se trouvait aussi une grande boule de marbre, d'à peu près sa taille.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: sommeil2

#choice: Pousser la boule vers le haut de la rue
#description: C'était la seule chose à faire.
#body: La femme se mit à pousser la boule.

Au début, elle était plus légère qu'elle ne semblait. Puis, au fur et à mesure que la femme la poussait, elle devint plus lourde. Fatalement, la femme dut lâcher la boule, qui roula en bas de la rue.

La femme reprit son souffle et redescendit vers la boule.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: sommeil2

#choice: S'effondrer, découragée
#description: C'en était trop.
#body: La femme tomba sur ses genoux, épuisée. Il n'y avait pas d'échappatoire. Elle n'avait plus qu'à attendre, ou continuer à tout jamais.

À ce moment-là, elle sentit une présence contre elle. Elle regarda. Un chat blanc s'était blotti contre elle, sorti de nulle part.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: sommeil3
