#room: Un rêve champêtre
#description: Dans les royaumes du rêve, les formes et idées défilaient librement. Cette nuit-ci, elles convergeaient vers un champ de blé.
#contents:

#choice: Regarder autour de soi
#description: Tout autour, des épis de blé à perte de vue. Au loin, une maison.
#body: Tout autour, des épis de blé jaunes s'étalaient à perte de vue. Le ciel était d'un bleu profond, barré de cumulus blancs immobiles. Il n'y avait pas de vent. Tout était immobile.

Au loin, la femme pouvait voir une maison au toit rouge. Elle la connaissait: c'était la sienne, lors de son enfance.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: sommeil1

#choice: Aller vers la maison au toit rouge
#description: La femme se mit en marche vers la maison...
#body: La femme se mit en marche vers la maison. C'était une ferme, elle pouvait voir les étables et la grange. La ferme semblait infiniment loin.

Deux personnes et un petit animal se tenaient devant la porte. Ils l'attendaient mais ne bougeaient pas non plus.

La femme marcha et marcha, mais elle ne se rapprocha jamais.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: sommeil1

#choice: Rêver d'autre chose
#description: Tout comme un rêve vient, il doit finir.
#body: La femme regarda à ses pieds. Un trou se formait dans le sol, plus loin devant.

Il s'élargit et s'élargit, jusqu'à ce qu'en pousse une grande plante grise en béton. Il lui poussa des fenêtres, des tuyaux et des antennes, et au fur et à mesure que le trou grandissait, d'autres immeubles poussèrent.

La femme courut sans pouvoir s'éloigner du gouffre. La campagne se fit avaler par la ville, et la femme tomba dans le néant noir du sommeil profond.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: sommeil2
