#room: Un rêve de compagnie
#description: Dans les royaumes du rêve, les formes et idées défilaient librement. Cette nuit-ci, elles avaient convergé vers un rocher en bas d'une rue en pente. Toutefois, à présent, la femme n'était plus seule.
#contents:

#choice: Regarder le nouvel arrivant
#description: Il était blanc, et il s'était blotti contre la femme pour dormir.
#body: C'était un chat au pelage d'un blanc immaculé. Il s'était blotti contre la femme pour dormir, et à présent il respirait paisiblement, ses yeux fermés sur de doux songes.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: sommeil3

#choice: Caresser le nouvel arrivant
#description: Il avait l'air si paisible.
#body: La femme, bougeant doucement, passa la main sur la tête du chat. Le chat ronronna doucement, avant de se blottir plus profondément contre elle.

La femme se sentait un petit peu mieux, maintenant.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: sommeil3

#choice: Regarder autour de soi
#description: La ville n'était plus aussi vide qu'avant.
#body: La femme regarda autour d'elle. La ville n'était plus aussi vide qu'avant. De toutes les directions, de toutes les fenêtres, des chats venaient.

Centaine par centaine, ils vinrent sans autre bruit que celui du tapotement de leurs pattes sur la chaussée, leurs pelages de toutes les couleurs.

Le chat endormi se réveilla, se leva et jeta un coup d'oeil vers la boule. Il fixa la femme quelques secondes puis cligna lentement des yeux, en attente qu'elle fasse quelque chose.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: sommeil4
