#room: Un rêve de compagnie
#description: Dans les royaumes du rêve, les formes et idées défilaient librement. Cette nuit-ci, elles avaient convergé vers un rocher en bas d'une rue en pente. Toutefois, à présent, la femme n'était plus seule.
#contents:

#choice: Pousser la boule de marbre
#description: Des renforts étaient arrivés.
#body: La femme se leva et commença à pousser la boule. Comme avant, la boule commença par être légère, mais elle s'alourdit bientôt.

Au moment ou la femme commençait à faiblir, les chats vinrent se joindre à elle pour pousser. La boule devenait de plus en plus lourde, mais les chats, sans un bruit, venaient de plus en plus nombreux pour aider, et poussaient la boule sans effort.

Ils poussaient, et poussaient, les chats contrant le poids de la boule. La femme sentit qu'ils allaient vaincre, qu'ils allaient arriver au bout de cette pente, leurs forces réunies, lorsqu'un bruit se détacha de l'effort silencieux.

Le bruit était d'abord à peine audible, puis devint plus fort. C'était un miaulement- non, c'était une voix. Elle disait quelque chose d'indistinct.

Le bruit se précisa; la voix répétait le même mot: "Humaine?"

La femme se réveilla en sursaut, mais le bruit resta, venant d'à côté d'elle.

Elle se tourna de côté et vit une paire d'yeux qui la fixaient. Un chat tigré la regardait, attendant à côté de son lit.

Le chat ouvrit la bouche et parla: "Humaine, j'ai besoin de toi."§
#image: none
#requirements: none
#visible: false
#sideeffects: unset enTrainDeDormir, set appartement, unset observeParChat
#next: chapitre2
