#room: Sur les toits de la ville
#description: Le chat guidait la femme sur les toits de la ville. Lui d'un pas léger et assuré, elle avec la peur de casser une tuile et de tomber.
#contents:

#choice: Regarder en bas
#description: Un gouffre se trouvait à quelques dizaines de centimètres des pieds de la femme.
#body: Un gouffre se trouvait à quelques dizaines de centimètres des pieds de la femme. Un pas de travers ou une tuile cassée et elle finirait en bas de la rue, en mauvais état. Malgré le danger, elle était curieuse: elle n'avait jamais vu la ville de cet angle-là; les lumières des fenêtres éclairaient leur passage, les toits formant autant de montagnes délimitant les combes sombres des rues en bas.

De ces toits, elle pouvait aller n'importe où, au lieu d'être confinée aux artères noires des rues. Le ciel était toujours opaque, mais il paraissait plus grand. Une douce brise soufflait sur la paire.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: appartementToit

#choice: Poursuivre son chemin
#description: Le chat s'agitait. Le temps pressait. Il fallait avancer.
#body: Après un long trajet sur les toits, ils arrivèrent vers un immeuble carré dont le toit plat était éclairé par une lampe située au milieu. Avant d'y aller, le chat dit à la femme:

"Nous y sommes. Ils ne seront pas très contents de nous voir, alors il ne faudra pas les provoquer. Ne fixe personne trop longtemps et évite les mouvements brusques. Je sais que c'est dur, mais j'espère que ça va marcher."

Elle n'en fut pas rassurée, ce dont il ne sembla pas prendre note. Il se tourna une dernière fois vers la femme:

"D'ailleurs, j'ai omis de faire les présentations. Je m'appelle Lucky."

Puis il sauta, et elle le suivit.

Le toit semblait vide, mais Lucky était nerveux. La femme comprit pourquoi lorsqu'elle vit les centaines de silhouettes grises qui les attendaient dans l'ombre des rebords.

Une silhouette s'avança, une chatte noire sortit de l'ombre d'un pas décidé. Elle émit un grondement menaçant à l'intention de Lucky, puis jeta un coup d'oeil vers la femme. En language humain, elle énonça d'un ton narquois:

"Tu es revenu, 'Lucky'. Avec une humaine. Dis-moi, quelle raison peux-tu nous donner de ne pas t'éviscérer?"

"J'ai quelque chose à dire, dit Lucky, et elle aussi."§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: assemblee1
