#room: Dire quelque chose, n'importe quoi
#description: Tous regardaient la femme. Il fallait répondre quelque chose. Mais dire quoi?
#contents:

#choice: "..."
#description: Rien ne venait.
#body: La femme resta silencieuse. Elle ne savait pas quoi dire. Mra la regarda:

"C'est ça que tu nous amènes, Lucky? Elle a l'air étrangement frappée de mutisme! Serait-ce parce qu'elle n'a rien à dire?"

Lucky regarda la femme, déçu mais pas surpris. Il tenta de sauver la situation:

"Laisse-lui du temps, elle a juste besoin de-"

"Lucky, ce dont ton humaine a besoin, c'est de nous comprendre. Tu l'as amenée sans qu'elle sache rien de nous, que veux-tu qu'elle dise? Ce n'est pas ça qui va nous convaincre. Tu étais désespéré d'apprendre que nous étions sur le point de partir au point de prendre la première personne qui venait?"

La femme cherchait encore quelque chose à dire. Mra lui dit:

"C'est inutile de chercher, humaine. Tu ne nous connais pas."

Lucky voulut argumenter:

"Écoute, Mra, je suis convaincu que-"

Mra le coupa: "Et toi, nous ne t'écouterons pas, tu n'as pas voix au chapitre, faiblard."

Elle réfléchit un moment, sonda la foule, puis se tourna à nouveau vers la femme.

"Toi, tu n'as rien à faire ici."§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: chapitre3
