#room: L'assemblée
#description: C'était une situation dangereuse. Qu'allait dire Lucky?
#contents:

#choice: "C'est une mauvaise idée de partir"
#description: Lucky continua: "Comme vous le savez, Mra ci-présente est arrivée il y a plusieurs mois..."
#body: Lucky continua: "Comme vous le savez, Mra ci-présente est arrivée il y a plusieurs mois de l'extérieur sauvage pour nous convaincre de nous libérer de nos maîtres humains."

Alentours, les chats restèrent silencieux. Aucune objection. Mra, la chatte noire, agita la queue en l'écoutant.

"Elle nous a dit que les humains nous opprimaient, que notre vraie nature était libre, et que nous devrions faire sécession de nos maîtres pour la suivre, pour sortir de la ville."

L'auditoire prolongea son écoute silencieuse. Tous se méfiaient de ce que Lucky allait dire.

"C'est une idée stupide. Peu d'entre nous sont prêts à la vie sauvage. Nous avons été élevés dans cette ville, dans ces appartements. Nous avons grandi dans la famille de nos maîtres. Qu'il y a-t-il pour nous à la campagne? Dans les forêts? Dans les montagnes? Dis-nous, Mra: Qu'est-ce que ça nous amène?"

Mra, fulminante, s'avança pour répondre.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: assemblee2
