#room: Répondre, vite
#description: Tous regardaient la femme 
#contents:

#choice: "Tu déformes tout"
#description: Fulminante, elle s'avança pour parler.
#body: Fulminante, Mra s'avança pour parler:

"Tu déformes tout, avorton. Tu as ignoré tout ce qui ne t'arrangeait pas, car tu es à la botte des humains. Tu viens avec le nom qu'ils t'ont donné et tu ronronnes dans leur pattes! Tu ne sais pas chasser, misérable intrus, toute ta sustenance, tu vas la chercher dans une gamelle! Tu sembles oublier les abus dont ont été victimes tant des nôtres; tu sembles oublier la vie de subalterne à laquelle les humains nous forcent; tu sembles omettre toutes ces choses, et je sais pourquoi: tu n'as pas d'arguments. Pas de raison de nous faire rester sous leur joug. Tu es tellement faible que tu dois te faire accompagner d'une humaine pour parler à ta place."

"Je ne dis que les faits. Ce dont tu m'accuses, d'être soumis aux humains, tu peux le dire de presque nous tous ici. Nous avons tous été nourris par gamelle, voire même par biberon, et regarde maintenant: plusieurs mois que cette petite révolte a commencé, et nous peinons à nous répartir les proies dans cette ville exiguë."

"Ce qui est pourquoi nous devons partir. Nous ne devons pas dépendre des humains et de leur bonnes grâces; elles ne sont que des masques derrière des intentions traîtresses. Jamais nous ne nous laisserons acheter pour un bol de lait!"

La foule des chats autour remua en approbation. Mra se tourna vers la femme:

"En parlant de cela, qu'as-tu à nous dire, humaine?"§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: assemblee3
