#room: L'assemblée
#description: C'était une situation dangereuse. Qu'allait dire Lucky?
#contents:

#choice: "C'est une mauvaise idée de partir"
#description: Lucky continua: "Comme vous le savez, Mra ci-présente est arrivée il y a plusieurs mois..."
#body: Lucky continua: "Comme vous le savez, Mra ci-présente est arrivée il y a plusieurs mois de l'extérieur pour nous convaincre de nous libérer de nos maîtres humains."§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: appartementToit
