#room: Chapitre 2: Tous les chats sont gris
#description: Le chat fixait la femme.
#contents:

#choice: "Tu peux parler?"
#description: Il était blanc, et il s'était blotti contre la femme pour dormir.
#body: C'était un chat au pelage d'un blanc immaculé. Il s'était blotti contre la femme pour dormir, et à présent il respirait paisiblement, ses yeux fermés sur de doux songes.§
#image: none
#requirements: none
#visible: false
#sideeffects: none
#next: sommeil3
