#variable: mainvar testVarImage
#onSet: Une variable dans le fichier principal.
#onUnset: Un meurtre!
#value: false

#room: Le début
#description: Ahahah lol.
#contents:

#choice: Faire un truc
#description: Jsp moi.
#body: Le château de senarclens est en afrique du sud.
Si, si, je vous assure.§
#image: roomImage
#requirements: no mainvar
#visible: false
#sideeffects: set anothervar, unset testvar
#next: testRoom
